---
abstract: "[One line description of module's purpose here]"
author: Jesse Vincent <jesse@bestpractical.com>
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-View-ConciseSpreadsheet
no_index:
  directory:
    - html
    - inc
    - t
requires:
  Test::More: 0
  Text::CSV_XS: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
